/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sessions/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 세션 후기 수정
         * @description 본인이 작성한 세션 후기를 수정합니다.
         */
        put: operations["updateComment"];
        post?: never;
        /**
         * 세션 후기 삭제
         * @description 본인이 작성한 세션 후기를 삭제(Soft Delete)합니다.
         */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 상세 조회
         * @description 프로젝트 ID를 통해 피그마 상세 화면에 필요한 정보를 조회합니다.
         */
        get: operations["getProjectDetail"];
        /**
         * 프로젝트 수정
         * @description 운영진 권한(LEADER, MANAGER)을 가진 사용자가 기존 프로젝트 정보를 전체 수정합니다.
         */
        put: operations["updateProject"];
        post?: never;
        /**
         * 프로젝트 삭제
         * @description 운영진 권한(LEADER, MANAGER)을 가진 사용자가 프로젝트를 삭제 처리합니다.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/recruitments/{recruitmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 모집 공고 수정
         * @description 기존 모집 공고의 일정, 상태, 모집 파트 정보를 수정합니다.
         */
        put: operations["updateRecruitment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 모집 질문 수정
         * @description 기존 모집 질문의 내용, 파트, 순서 등을 수정합니다.
         */
        put: operations["updateQuestion"];
        post?: never;
        /**
         * 모집 질문 삭제
         * @description 특정 모집 질문을 삭제합니다.
         */
        delete: operations["deleteQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stamps/missions/{missionId}/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 스탬프 미션 인증 (사진 업로드 + 소감 작성) */
        post: operations["authenticateMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션 후기 목록 조회
         * @description 해당 세션에 작성된 삭제되지 않은 후기 목록을 조회합니다.
         */
        get: operations["getComments"];
        put?: never;
        /**
         * 세션 후기 작성
         * @description 부원(MEMBER, LEADER, MANAGER) 권한을 가진 사용자가 후기를 작성합니다.
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recruitments/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 모집 시작 사전 알림 신청
         * @description 사용자가 이메일을 입력하여 다음 기수 모집 알림을 신청합니다.
         */
        post: operations["registerAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 목록 조회
         * @description 기수(term) 필터링 및 페이징 목록을 조회합니다. (기본 9개씩 조회)
         */
        get: operations["getProjects"];
        put?: never;
        /**
         * 프로젝트 생성
         * @description 운영진 권한(LEADER, MANAGER)을 가진 사용자가 새로운 프로젝트를 등록합니다.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/member-profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 프로필 조회
         * @description 현재 사용자의 특정 기수 프로필을 조회합니다.
         */
        get: operations["getMyProfile"];
        put?: never;
        /**
         * 내 프로필 등록
         * @description 현재 사용자의 기수별 부원 프로필을 등록합니다.
         */
        post: operations["createMyProfile"];
        /**
         * 내 프로필 삭제
         * @description 현재 사용자의 특정 기수 프로필을 삭제합니다.
         */
        delete: operations["deleteMyProfile"];
        options?: never;
        head?: never;
        /**
         * 내 프로필 수정
         * @description 현재 사용자의 특정 기수 프로필을 부분 수정합니다.
         */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/api/v1/applications/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지원서 최종 제출
         * @description 지원서를 최종 제출합니다. (필수 답변 및 글자 수 검증)
         */
        post: operations["submitApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지원서 첨부파일(포트폴리오) S3 업로드
         * @description 파일 업로드 성공 시 반환된 S3 URL을 지원서 답변(content)에 넣어 저장/제출합니다.
         */
        post: operations["uploadApplicationFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지원서 임시저장
         * @description 작성 중인 지원서를 임시 저장합니다. (필수 항목 미입력 허용)
         */
        post: operations["saveDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stamps/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자 - 스탬프 미션 생성
         * @description 새로운 스탬프 미션들을 등록합니다.
         */
        post: operations["createMissions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/recruitments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 모집 공고 생성
         * @description 새로운 기수의 모집 공고 및 모집 파트를 등록합니다.
         */
        post: operations["createRecruitment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/recruitments/{recruitmentId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 모집 질문 일괄 등록
         * @description 모집 공고에 속한 질문 목록을 일괄 등록합니다.
         */
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/faqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * FAQ 등록
         * @description 새로운 FAQ를 등록합니다. partId가 null이면 공통 FAQ로 등록됩니다.
         */
        post: operations["createFaq"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로컬 회원가입 */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** accessToken 재발급 */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로컬 로그인 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 구글 로그인 */
        post: operations["googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 인증코드 확인 */
        post: operations["verifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/verification-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 인증코드 전송 */
        post: operations["sendVerificationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stamps/missions/{missionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 관리자 - 스탬프 미션 삭제
         * @description 스탬프 미션을 삭제합니다.
         */
        delete: operations["deleteMission"];
        options?: never;
        head?: never;
        /**
         * 관리자 - 스탬프 미션 수정
         * @description 스탬프 미션 정보를 수정합니다.
         */
        patch: operations["updateMission"];
        trace?: never;
    };
    "/api/v1/admin/faqs/{faqId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * FAQ 삭제
         * @description FAQ를 삭제합니다.
         */
        delete: operations["deleteFaq"];
        options?: never;
        head?: never;
        /**
         * FAQ 수정
         * @description 기존 FAQ의 파트 지정, 질문, 답변을 수정합니다.
         */
        patch: operations["updateFaq"];
        trace?: never;
    };
    "/api/v1/admin/applications/{applicationId}/pass-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 합/불 상태 변경
         * @description 지원서의 id를 입력하면 passStatus를 변경합니다.passStatus는 PENDING / DOC_PASS / DOC_FAIL / FINAL_PASS / FINAL_FAIL 가 존재합니다.
         */
        patch: operations["updatePassStatus"];
        trace?: never;
    };
    "/api/mypage/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프로필 불러오기 */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 프로필 텍스트 정보 수정
         * @description 이름/전공/학번/전화번호를 수정합니다.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/mypage/profile/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 프로필 이미지 수정
         * @description 프로필 이미지 파일을 교체합니다.
         */
        patch: operations["updateProfileImage"];
        trace?: never;
    };
    "/api/auth/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 역할 변경
         * @description 리더가 특정 사용자의 역할(ROLE_ADMIN/ROLE_MEMBER)을 변경합니다.
         */
        patch: operations["changeRole"];
        trace?: never;
    };
    "/api/v1/stamps/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스탬프 미션 목록 조회
         * @description 기수 미입력 시 DB의 최신 기수 미션을 조회합니다.
         */
        get: operations["getMissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stamps/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 스탬프 목록 조회 */
        get: operations["getMyStamps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션 목록 조회
         * @description 기수(term) 및 파트(part) 기준 세션 목록을 조회합니다.
         */
        get: operations["getSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 세션 상세 조회
         * @description 기수, 파트, 주차 정보를 통해 세션 상세 정보를 조회합니다.
         */
        get: operations["getSessionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recruitments/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 랜딩페이지 모집 정보 조회
         * @description 현재 모집 공고 일정, 파트 목록, FAQ 정보를 한 번에 조회합니다.
         */
        get: operations["getLandingPageInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recruitments/current/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원서 질문 목록 조회
         * @description 현재 진행 중인 모집 공고의 공통 및 파트별 질문 목록을 조회합니다.
         */
        get: operations["getCurrentQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/member-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 부원 목록 조회
         * @description 기수와 선택 필터로 부원 프로필 목록을 조회합니다.
         */
        get: operations["getProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/member-profiles/{profileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 부원 상세 조회
         * @description 프로필 ID로 부원 프로필을 조회합니다.
         */
        get: operations["getProfile_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home/recruitments/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 모집 정보 조회
         * @description 홈 화면에 표시할 지원 가능 여부와 마감 D-Day를 조회합니다.
         */
        get: operations["getCurrentRecruitment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최근 프로젝트 조회
         * @description 홈 화면에 표시할 프로젝트를 최신 등록 순으로 조회합니다.
         */
        get: operations["getRecentProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 지원서 조회
         * @description 현재 진행 중인 모집 공고에 작성 중이거나 제출한 내 지원서를 조회합니다.
         */
        get: operations["getMyApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 지원서 목록 조회
         * @description 전체 지원서 목록을 조회합니다. term, partId, passStatus를 선택적으로 입력할 수 있습니다. term을 입력하지 않으면 가장 최신 생성된 term으로 불러옵니다.passStatus는 PENDING / DOC_PASS / DOC_FAIL / FINAL_PASS / FINAL_FAIL 가 존재합니다.
         */
        get: operations["getApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원서 상세 조회
         * @description 지원서의 id를 입력하면 상세 조회가 가능합니다.
         */
        get: operations["getApplicationDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mypage/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원 현황 조회
         * @description status=SUBMITTED: 제출완료 지원서 목록(List). status=DRAFT: 임시저장 지원서 단일 객체(최대 1개).
         */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mypage/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 임시저장 지원서 불러오기 */
        get: operations["getApplicationDetail_1"];
        put?: never;
        post?: never;
        /**
         * 지원서 삭제
         * @description 임시저장 상태의 지원서만 삭제 가능합니다.
         */
        delete: operations["deleteApplication"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionCommentCreateUpdateRequest: {
            content: string;
        };
        ApiResponseSessionCommentResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["SessionCommentResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        SessionCommentResponse: {
            /** Format: int64 */
            commentId?: number;
            /** Format: int64 */
            userId?: number;
            userName?: string;
            profileImageUrl?: string;
            content?: string;
            isOwner?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ProjectCreateUpdateRequest: {
            /** Format: int32 */
            term: number;
            /** @enum {string} */
            hackathon: "IDEATHON" | "HERETHON" | "CENTRALTHON";
            title: string;
            summary: string;
            description: string;
            startMonth: string;
            endMonth: string;
            logoUrl: string;
            slideUrls: string[];
            members: components["schemas"]["ProjectMemberRequest"][];
            techStackIds: number[];
        };
        ProjectMemberRequest: {
            name: string;
            /** @enum {string} */
            part: "PM" | "FRONTEND" | "BACKEND";
        };
        ApiResponseProjectCreateUpdateResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ProjectCreateUpdateResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ProjectCreateUpdateResponse: {
            /** Format: int64 */
            projectId?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminRecruitmentPartRequest: {
            /** Format: int64 */
            id?: number;
            name: string;
            description?: string;
        };
        AdminRecruitmentRequest: {
            /** Format: int32 */
            term: number;
            title: string;
            /** @enum {string} */
            status: "UPCOMING" | "OPEN" | "CLOSED";
            /** Format: date-time */
            docStartAt: string;
            /** Format: date-time */
            docEndAt: string;
            /** Format: date-time */
            docResultAt: string;
            /** Format: date-time */
            interviewStartAt: string;
            /** Format: date-time */
            interviewEndAt: string;
            /** Format: date-time */
            finalResultAt: string;
            parts?: components["schemas"]["AdminRecruitmentPartRequest"][];
            validScheduleSequence?: boolean;
        };
        AdminRecruitmentResponse: {
            /** Format: int64 */
            recruitmentId?: number;
            /** Format: int32 */
            term?: number;
            title?: string;
            /** @enum {string} */
            status?: "UPCOMING" | "OPEN" | "CLOSED";
            /** Format: date-time */
            docStartAt?: string;
            /** Format: date-time */
            docEndAt?: string;
            /** Format: date-time */
            docResultAt?: string;
            /** Format: date-time */
            interviewStartAt?: string;
            /** Format: date-time */
            interviewEndAt?: string;
            /** Format: date-time */
            finalResultAt?: string;
            /** Format: date-time */
            createdAt?: string;
            parts?: components["schemas"]["RecruitmentPartResponse"][];
        };
        ApiResponseAdminRecruitmentResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["AdminRecruitmentResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        RecruitmentPartResponse: {
            /** Format: int64 */
            partId?: number;
            name?: string;
            description?: string;
        };
        AdminQuestionRequest: {
            /** Format: int64 */
            partId?: number;
            /** Format: int64 */
            questionNumber: number;
            content: string;
            /** Format: int32 */
            maxLength: number;
            /** @enum {string} */
            questionType: "SHORT_ANSWER" | "LONG_ANSWER" | "FILE" | "LINK";
            isRequired: boolean;
        };
        AdminQuestionResponse: {
            /** Format: int64 */
            questionId?: number;
            /** Format: int64 */
            recruitmentId?: number;
            /** Format: int64 */
            partId?: number;
            /** Format: int64 */
            questionNumber?: number;
            content?: string;
            /** Format: int32 */
            maxLength?: number;
            /** @enum {string} */
            questionType?: "SHORT_ANSWER" | "LONG_ANSWER" | "FILE" | "LINK";
            isRequired?: boolean;
        };
        ApiResponseAdminQuestionResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["AdminQuestionResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        StampAuthRequest: {
            /** Format: binary */
            image: string;
            /** Format: date */
            authDate: string;
            content: string;
        };
        ApiResponseStampAuthResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["StampAuthResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        StampAuthResponse: {
            /** Format: int64 */
            userStampId?: number;
            /** Format: int64 */
            missionId?: number;
            stampImageUrl?: string;
            /** Format: date-time */
            attainedAt?: string;
        };
        RecruitmentAlertRequest: {
            /** Format: email */
            email: string;
        };
        ApiResponseVoid: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: unknown;
            /** Format: date-time */
            timestamp?: string;
        };
        MemberProfileCreateRequest: {
            /** Format: int32 */
            term: number;
            name: string;
            department: string;
            studentId: string;
            /** @enum {string} */
            memberGroup: "LEADERSHIP" | "PM" | "BE" | "FE";
            /** @enum {string} */
            memberType: "STAFF" | "BABY_LION";
            /** @enum {string} */
            position: "PRESIDENT" | "VICE_PRESIDENT" | "PART_LEADER" | "NONE";
            profileImageUrl?: string;
            introduction?: string;
            githubUrl?: string;
            instagramUrl?: string;
        };
        ApiResponseMemberProfileDetailResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MemberProfileDetailResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        MemberProfileDetailResponse: {
            /** Format: int64 */
            profileId?: number;
            /** Format: int32 */
            term?: number;
            name?: string;
            department?: string;
            studentId?: string;
            departmentStudentId?: string;
            /** @enum {string} */
            memberGroup?: "LEADERSHIP" | "PM" | "BE" | "FE";
            /** @enum {string} */
            memberType?: "STAFF" | "BABY_LION";
            /** @enum {string} */
            position?: "PRESIDENT" | "VICE_PRESIDENT" | "PART_LEADER" | "NONE";
            profileImageUrl?: string;
            introduction?: string;
            githubUrl?: string;
            instagramUrl?: string;
        };
        AnswerInput: {
            /** Format: int64 */
            questionId?: number;
            content?: string;
        };
        ApplicationSaveRequest: {
            /** Format: int64 */
            partId?: number;
            answers?: components["schemas"]["AnswerInput"][];
        };
        ApiResponseLong: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            /** Format: int64 */
            result?: number;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseString: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        MissionCreateRequest: {
            missions: components["schemas"]["MissionItemRequest"][];
        };
        MissionItemRequest: {
            title: string;
            description: string;
            /** Format: int32 */
            term: number;
            imageUrl: string;
            stampUrl: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        ApiResponseListMissionResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MissionResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        MissionResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** Format: int32 */
            term?: number;
            imageUrl?: string;
            stampUrl?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** @enum {string} */
            status?: "UPCOMING" | "IN_PROGRESS" | "ENDED";
        };
        ApiResponseListAdminQuestionResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["AdminQuestionResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        FaqItemRequest: {
            /** Format: int64 */
            partId?: number;
            question: string;
            answer: string;
        };
        FaqRequest: {
            /** Format: int64 */
            recruitmentId: number;
            faqs: components["schemas"]["FaqItemRequest"][];
        };
        ApiResponseListFaqResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FaqResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        FaqResponse: {
            /** Format: int64 */
            recruitmentId?: number;
            /** Format: int64 */
            faqId?: number;
            /** Format: int64 */
            partId?: number;
            question?: string;
            answer?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        SignupRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            passwordCheck: string;
        };
        ApiResponseUserResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["UserResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        UserResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            email?: string;
            role?: string;
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            accessTokenExpiresIn?: number;
        };
        TokenRefreshRequest: {
            refreshToken: string;
        };
        ApiResponseTokenRefreshResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["TokenRefreshResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        TokenRefreshResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            accessTokenExpiresIn?: number;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        GoogleLoginRequest: {
            idToken: string;
        };
        ApiResponseGoogleLoginResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["GoogleLoginResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        GoogleLoginResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            role?: string;
            accessToken?: string;
            refreshToken?: string;
            isNewUser?: boolean;
        };
        EmailVerificationRequest: {
            /** Format: email */
            email: string;
            code: string;
        };
        ApiResponseEmailVerificationResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["EmailVerificationResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        EmailVerificationResponse: {
            email?: string;
            verified?: boolean;
        };
        EmailCodeSendRequest: {
            /** Format: email */
            email: string;
        };
        ApiResponseEmailCodeSendResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["EmailCodeSendResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        EmailCodeSendResponse: {
            email?: string;
            /** Format: int32 */
            expiresIn?: number;
        };
        MemberProfileUpdateRequest: {
            name?: string;
            department?: string;
            studentId?: string;
            /** @enum {string} */
            memberGroup?: "LEADERSHIP" | "PM" | "BE" | "FE";
            /** @enum {string} */
            memberType?: "STAFF" | "BABY_LION";
            /** @enum {string} */
            position?: "PRESIDENT" | "VICE_PRESIDENT" | "PART_LEADER" | "NONE";
            profileImageUrl?: string;
            introduction?: string;
            githubUrl?: string;
            instagramUrl?: string;
        };
        MissionUpdateRequest: {
            title: string;
            description: string;
            /** Format: int32 */
            term: number;
            imageUrl: string;
            stampUrl: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        ApiResponseMissionResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MissionResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        FaqUpdateRequest: {
            /** Format: int64 */
            partId?: number;
            question: string;
            answer: string;
        };
        ApiResponseFaqResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FaqResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        UpdatePassStatusRequest: {
            /** @enum {string} */
            passStatus: "PENDING" | "DOC_PASS" | "DOC_FAIL" | "FINAL_PASS" | "FINAL_FAIL";
        };
        ProfileUpdateRequest: {
            /**
             * @description 이름
             * @example 홍길동
             */
            name: string;
            major: string;
            studentId: string;
            phoneNumber: string;
        };
        ApiResponseProfileUpdateResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ProfileUpdateResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ProfileUpdateResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            major?: string;
            studentId?: string;
            phoneNumber?: string;
        };
        ApiResponseProfileImageUpdateResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ProfileImageUpdateResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ProfileImageUpdateResponse: {
            profileImageUrl?: string;
        };
        RoleChangeRequest: {
            role?: string;
        };
        ApiResponseRoleChangeResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["RoleChangeResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        RoleChangeResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            role?: string;
        };
        ApiResponseListMissionListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MissionListResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        MissionListResponse: {
            /** Format: int64 */
            missionId?: number;
            title?: string;
            description?: string;
            imageUrl?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            isCompleted?: boolean;
        };
        ApiResponseMyStampResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MyStampResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        MyStampResponse: {
            userName?: string;
            /** Format: int32 */
            totalStampCount?: number;
            stamps?: components["schemas"]["StampItem"][];
        };
        StampItem: {
            /** Format: int64 */
            userStampId?: number;
            /** Format: int64 */
            missionId?: number;
            missionTitle?: string;
            stampImageUrl?: string;
            /** Format: date */
            authDate?: string;
        };
        ApiResponseSessionListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["SessionListResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        SessionListResponse: {
            /** Format: int32 */
            term?: number;
            part?: string;
            sessions?: components["schemas"]["SessionSummaryResponse"][];
        };
        SessionSummaryResponse: {
            /** Format: int64 */
            sessionId?: number;
            /** Format: int32 */
            weekNumber?: number;
            title?: string;
            subTitle?: string;
        };
        ApiResponseListSessionCommentResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["SessionCommentResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseSessionDetailResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["SessionDetailResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        LearningTopicResponse: {
            /** Format: int64 */
            learningTopicId?: number;
            content?: string;
            /** Format: int32 */
            sequenceNum?: number;
        };
        SessionDetailResponse: {
            /** Format: int64 */
            sessionId?: number;
            /** Format: int32 */
            term?: number;
            /** Format: int32 */
            weekNumber?: number;
            part?: string;
            title?: string;
            subTitle?: string;
            content?: string;
            thumbnailUrl?: string;
            learningTopics?: components["schemas"]["LearningTopicResponse"][];
        };
        ApiResponseLandingPageResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["LandingPageResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        FaqInfo: {
            /** Format: int64 */
            faqId?: number;
            /** Format: int64 */
            partId?: number;
            question?: string;
            answer?: string;
        };
        LandingPageResponse: {
            recruitment?: components["schemas"]["RecruitmentInfo"];
            parts?: components["schemas"]["PartInfo"][];
            faqs?: components["schemas"]["FaqInfo"][];
        };
        PartInfo: {
            /** Format: int64 */
            partId?: number;
            name?: string;
            description?: string;
        };
        RecruitmentInfo: {
            /** Format: int64 */
            recruitmentId?: number;
            /** Format: int32 */
            term?: number;
            title?: string;
            /** @enum {string} */
            status?: "UPCOMING" | "OPEN" | "CLOSED";
            /** Format: date-time */
            docStartAt?: string;
            /** Format: date-time */
            docEndAt?: string;
            /** Format: date-time */
            docResultAt?: string;
            /** Format: date-time */
            interviewStartAt?: string;
            /** Format: date-time */
            interviewEndAt?: string;
            /** Format: date-time */
            finalResultAt?: string;
        };
        ApiResponseCurrentQuestionsResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CurrentQuestionsResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        CurrentQuestionsResponse: {
            /** Format: int64 */
            recruitmentId?: number;
            /** Format: int32 */
            term?: number;
            commonQuestions?: components["schemas"]["QuestionInfo"][];
            partQuestions?: components["schemas"]["PartQuestionGroup"][];
        };
        PartQuestionGroup: {
            /** Format: int64 */
            partId?: number;
            partName?: string;
            questions?: components["schemas"]["QuestionInfo"][];
        };
        QuestionInfo: {
            /** Format: int64 */
            questionId?: number;
            /** Format: int64 */
            questionNumber?: number;
            content?: string;
            /** @enum {string} */
            questionType?: "SHORT_ANSWER" | "LONG_ANSWER" | "FILE" | "LINK";
            /** Format: int32 */
            maxLength?: number;
            isRequired?: boolean;
        };
        ApiResponsePageResponseProjectListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["PageResponseProjectListResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        PageResponseProjectListResponse: {
            content?: components["schemas"]["ProjectListResponse"][];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            isLast?: boolean;
        };
        ProjectListResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            summary?: string;
            logoUrl?: string;
        };
        ApiResponseProjectDetailResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ProjectDetailResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ProjectDetailResponse: {
            /** Format: int64 */
            id?: number;
            logoUrl?: string;
            title?: string;
            summary?: string;
            description?: string;
            /** @enum {string} */
            hackathon?: "IDEATHON" | "HERETHON" | "CENTRALTHON";
            startMonth?: string;
            endMonth?: string;
            slideUrls?: string[];
            membersByPart?: {
                [key: string]: string[];
            };
            techStacksByCategory?: {
                [key: string]: components["schemas"]["TechStackDto"][];
            };
        };
        TechStackDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        ApiResponseListMemberProfileListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MemberProfileListResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        MemberProfileListResponse: {
            /** Format: int64 */
            profileId?: number;
            /** Format: int32 */
            term?: number;
            name?: string;
            departmentStudentId?: string;
            /** @enum {string} */
            memberGroup?: "LEADERSHIP" | "PM" | "BE" | "FE";
            /** @enum {string} */
            memberType?: "STAFF" | "BABY_LION";
            /** @enum {string} */
            position?: "PRESIDENT" | "VICE_PRESIDENT" | "PART_LEADER" | "NONE";
            profileImageUrl?: string;
        };
        ApiResponseCurrentRecruitmentResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CurrentRecruitmentResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        CurrentRecruitmentResponse: {
            /** Format: int64 */
            recruitmentId?: number;
            /** Format: int32 */
            term?: number;
            title?: string;
            recruiting?: boolean;
            dDay?: string;
            /** @enum {string} */
            action?: "APPLY" | "NOTIFICATION";
        };
        ApiResponseListRecentProjectResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["RecentProjectResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        RecentProjectResponse: {
            /** Format: int64 */
            projectId?: number;
            title?: string;
            summary?: string;
            thumbnailUrl?: string;
        };
        AnswerDetail: {
            /** Format: int64 */
            answerId?: number;
            /** Format: int64 */
            questionId?: number;
            /** Format: int64 */
            questionNumber?: number;
            questionContent?: string;
            answerContent?: string;
        };
        ApiResponseMyApplicationResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MyApplicationResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApplicantInfo: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            email?: string;
            phone?: string;
            department?: string;
            studentId?: string;
        };
        MyApplicationResponse: {
            /** Format: int64 */
            applicationId?: number;
            /** Format: int32 */
            recruitmentTerm?: number;
            applicant?: components["schemas"]["ApplicantInfo"];
            part?: components["schemas"]["PartInfo"];
            /** @enum {string} */
            submitStatus?: "DRAFT" | "SUBMITTED";
            /** Format: date-time */
            savedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            answers?: components["schemas"]["AnswerDetail"][];
        };
        AdminApplicationListResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            size?: number;
            applications?: components["schemas"]["ApplicationSummary"][];
        };
        ApiResponseAdminApplicationListResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["AdminApplicationListResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApplicationSummary: {
            /** Format: int64 */
            applicationId?: number;
            applicantName?: string;
            studentId?: string;
            partName?: string;
            /** @enum {string} */
            submitStatus?: "DRAFT" | "SUBMITTED";
            /** @enum {string} */
            passStatus?: "PENDING" | "DOC_PASS" | "DOC_FAIL" | "FINAL_PASS" | "FINAL_FAIL";
            /** Format: date-time */
            submittedAt?: string;
        };
        AdminApplicationDetailResponse: {
            /** Format: int64 */
            applicationId?: number;
            /** Format: int32 */
            recruitmentTerm?: number;
            applicant?: components["schemas"]["ApplicantInfo"];
            part?: components["schemas"]["PartInfo"];
            /** @enum {string} */
            submitStatus?: "DRAFT" | "SUBMITTED";
            /** @enum {string} */
            passStatus?: "PENDING" | "DOC_PASS" | "DOC_FAIL" | "FINAL_PASS" | "FINAL_FAIL";
            /** Format: date-time */
            submittedAt?: string;
            answers?: components["schemas"]["AnswerDetailInfo"][];
        };
        AnswerDetailInfo: {
            /** Format: int64 */
            questionId?: number;
            /** Format: int64 */
            questionNumber?: number;
            questionContent?: string;
            answerContent?: string;
        };
        ApiResponseAdminApplicationDetailResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["AdminApplicationDetailResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseMypageResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MypageResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        MypageResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            profileImageUrl?: string;
            greeting?: string;
            email?: string;
            major?: string;
            studentId?: string;
            phoneNumber?: string;
            joinedAt?: string;
            role?: string;
        };
        ApiResponseObject: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: unknown;
            /** Format: date-time */
            timestamp?: string;
        };
        AnswerItem: {
            /** Format: int64 */
            questionId?: number;
            question?: string;
            content?: string;
        };
        ApiResponseApplicationDetailResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ApplicationDetailResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApplicationDetailResponse: {
            /** Format: int64 */
            applicationId?: number;
            /** Format: int64 */
            recruitmentId?: number;
            status?: string;
            /** Format: int64 */
            partId?: number;
            partName?: string;
            answers?: components["schemas"]["AnswerItem"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseApplicationDeleteResponse: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ApplicationDeleteResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApplicationDeleteResponse: {
            /** Format: int64 */
            applicationId?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCommentCreateUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSessionCommentResponse"];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getProjectDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectDetailResponse"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectCreateUpdateResponse"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateRecruitment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruitmentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRecruitmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminRecruitmentResponse"];
                };
            };
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminQuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminQuestionResponse"];
                };
            };
        };
    };
    deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    authenticateMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                missionId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["StampAuthRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStampAuthResponse"];
                };
            };
        };
    };
    getComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListSessionCommentResponse"];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCommentCreateUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSessionCommentResponse"];
                };
            };
        };
    };
    registerAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruitmentAlertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getProjects: {
        parameters: {
            query?: {
                /**
                 * @description 기수 필터 (미입력 시 전체 조회)
                 * @example 14
                 */
                term?: number;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseProjectListResponse"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProjectCreateUpdateResponse"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query: {
                term: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMemberProfileDetailResponse"];
                };
            };
        };
    };
    createMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberProfileCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMemberProfileDetailResponse"];
                };
            };
        };
    };
    deleteMyProfile: {
        parameters: {
            query: {
                term: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateMyProfile: {
        parameters: {
            query: {
                term: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMemberProfileDetailResponse"];
                };
            };
        };
    };
    submitApplication: {
        parameters: {
            query?: {
                userId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    uploadApplicationFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    saveDraft: {
        parameters: {
            query?: {
                userId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    createMissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMissionResponse"];
                };
            };
        };
    };
    createRecruitment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRecruitmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminRecruitmentResponse"];
                };
            };
        };
    };
    createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recruitmentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminQuestionRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAdminQuestionResponse"];
                };
            };
        };
    };
    createFaq: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaqRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListFaqResponse"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenRefreshResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGoogleLoginResponse"];
                };
            };
        };
    };
    verifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerificationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmailVerificationResponse"];
                };
            };
        };
    };
    sendVerificationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailCodeSendRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEmailCodeSendResponse"];
                };
            };
        };
    };
    deleteMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                missionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                missionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMissionResponse"];
                };
            };
        };
    };
    deleteFaq: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faqId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateFaq: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faqId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaqUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFaqResponse"];
                };
            };
        };
    };
    updatePassStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePassStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMypageResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProfileUpdateResponse"];
                };
            };
        };
    };
    updateProfileImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 변경할 프로필 이미지 파일 (jpg/png)
                     */
                    image: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProfileImageUpdateResponse"];
                };
            };
        };
    };
    changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleChangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRoleChangeResponse"];
                };
            };
        };
    };
    getMissions: {
        parameters: {
            query?: {
                term?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMissionListResponse"];
                };
            };
        };
    };
    getMyStamps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMyStampResponse"];
                };
            };
        };
    };
    getSessions: {
        parameters: {
            query: {
                /**
                 * @description 기수 필터
                 * @example 14
                 */
                term: number;
                /**
                 * @description 파트 필터 (BACKEND, FRONTEND, PM)
                 * @example PM
                 */
                part: "PM" | "FRONTEND" | "BACKEND";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSessionListResponse"];
                };
            };
        };
    };
    getSessionDetail: {
        parameters: {
            query: {
                /**
                 * @description 기수
                 * @example 14
                 */
                term: number;
                /**
                 * @description 파트 (BACKEND, FRONTEND, PM)
                 * @example PM
                 */
                part: "PM" | "FRONTEND" | "BACKEND";
                /**
                 * @description 주차 번호
                 * @example 1
                 */
                weekNumber: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSessionDetailResponse"];
                };
            };
        };
    };
    getLandingPageInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLandingPageResponse"];
                };
            };
        };
    };
    getCurrentQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCurrentQuestionsResponse"];
                };
            };
        };
    };
    getProfiles: {
        parameters: {
            query: {
                term: number;
                memberGroup?: "LEADERSHIP" | "PM" | "BE" | "FE";
                memberType?: "STAFF" | "BABY_LION";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMemberProfileListResponse"];
                };
            };
        };
    };
    getProfile_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMemberProfileDetailResponse"];
                };
            };
        };
    };
    getCurrentRecruitment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCurrentRecruitmentResponse"];
                };
            };
        };
    };
    getRecentProjects: {
        parameters: {
            query?: {
                /**
                 * @description 조회 개수 (기본 3개, 최대 10개)
                 * @example 3
                 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListRecentProjectResponse"];
                };
            };
        };
    };
    getMyApplication: {
        parameters: {
            query?: {
                userId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMyApplicationResponse"];
                };
            };
        };
    };
    getApplications: {
        parameters: {
            query?: {
                term?: number;
                partId?: number;
                passStatus?: "PENDING" | "DOC_PASS" | "DOC_FAIL" | "FINAL_PASS" | "FINAL_FAIL";
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminApplicationListResponse"];
                };
            };
        };
    };
    getApplicationDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminApplicationDetailResponse"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query: {
                status: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseObject"];
                };
            };
        };
    };
    getApplicationDetail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseApplicationDetailResponse"];
                };
            };
        };
    };
    deleteApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseApplicationDeleteResponse"];
                };
            };
        };
    };
}
